---
- name: Run Optional Versioncheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Add apt repos and install rspamd
  ansible.builtin.include_tasks:
    file: 'packages.yml'
  when: ansible_os_family == 'Debian'

- name: Configure rspamd
  ansible.builtin.include_tasks:
    file: 'configure.yml'

- name: Rspamd dkim signing
  ansible.builtin.include_tasks:
    file: 'dkim.yml'
  when: rspamd__configure_dkim | bool

- name: Redis backend
  ansible.builtin.include_tasks:
    file: 'redis.yml'
  when: rspamd__configure_redis | bool
