---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: add apt repos and install rspamd
  include_tasks: packages.yml
  when: ansible_os_family == 'Debian'

- name: configure rspamd
  include_tasks: configure.yml

- name: rspamd dkim signing
  include_tasks: dkim.yml

- name: redis backend
  include_tasks: redis.yml
