---
- name: Run sudo apt update
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Run systemctl restart rspamd
  become: true
  ansible.builtin.systemd:
    name: 'rspamd'
    state: 'reloaded'
